### ISSUE TITLE
Why do you rescale the inputs to the model using (2*input - 1)? 

### ISSUE THREAD

**Issue by kawshik8** [ermongroup/ncsnv2#5]
If this is done before adding noise, I understand it might be done to match the distribution of the gaussian which consists of both positive and negative values. However, this is done after adding the noise. So what is the reason?

**Comment by yang-song** [comment]
Great question! The scaling was historically used to transform the scale of images from [0, 1] to [-1, 1], so that inputs to the backbone are centered. Our implementation works reasonably well, but it is probably not the optimal implementation, and this scaling is probably even not needed. In hindsight, it is better to preprocess images to the scale of [-1, 1] before adding noise and feeding to the score network.

**Comment by kawshik8** [comment]
Thanks for the clarification :)
